### ISSUE TITLE
应用任务栏图标错误

### ISSUE THREAD

**Issue by kmyuhkyuk** [Direct5dom/WinWoL#1]
![image](https://github.com/Direct5dom/WinWoL/assets/72241714/2d2b074d-10bf-45fd-83bd-8d0b4e9c42b6)
小问题, 只是不美观

**Comment by sixiaolong1117** [comment]
已经解决，问题可能是因为不同比例图标缺失所致，现已对所有比例的图标重新生成，您可以尝试[WinWoL v1.1.1.0](https://github.com/Direct5dom/WinWoL/releases/tag/1.1.1.0)。
微软商店版本已经提交，距离过审可能需要一定的时间。
